### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by quadratecode** [JoelNiklaus/SwissCourtRulingCorpus#109]
Hi Joel

I hope this message finds you well - really cool project! I am interested in using some of the code from this repo in something I am working on. However, I was unable to find any information about the license under which the code is distributed. I probably missed it but if not: Would you consider adding a LICENSE.md?

All the best
Roger

**Comment by JoelNiklaus** [comment]
Hi Roger,

Thank you very much for your interest. Sure, I just added a License.

Cheers,
Joel
